spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: ${OAUTH2_CLIENT_NAME:fitwedding_client}
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

oauth:
  google:
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    token-uri: ${OAUTH2_GOOGLE_TOKEN_URI:https://oauth2.googleapis.com/token}
    userinfo-uri: ${OAUTH2_GOOGLE_USERINFO_URI:https://www.googleapis.com/oauth2/v3/userinfo}

